<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MedicineSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('medicines')->insert([
            ['generic_name' => 'fentanil inj',
            'form' => 'inj 0,05 mg/mL (i.m./i.v.)',
            'restriction_formula' => '5 amp/kasus',
            'description' => 'hanya untuk nyeri berat dan harus diberikan oleh tim medis yang dapat melakukan 
            resusitasi.',
            'faskes_tk1' => false,
            'faskes_tk2' => true,
            'faskes_tk3' => true,
            'category_id' => 3],
            ['generic_name' => 'fentanil patch 12,5 mcg/jam',
            'form' => 'patch 12,5 mcg/jam',
            'restriction_formula' => '10 patch/bulan.',
            'description' => 'Untuk nyeri kronik pada 
            pasien kanker yang tidak 
            terkendali, dan tidak untuk nyeri akut',
            'faskes_tk1' => false,
            'faskes_tk2' => true,
            'faskes_tk3' => true,
            'category_id' => 3],
            ['generic_name' => 'fentanil patch 25 mcg/jam',
            'form' => 'patch 25 mcg/jam',
            'restriction_formula' => '10 patch/bulan.',
            'description' => 'Untuk nyeri kronik pada 
            pasien kanker yang tidak 
            terkendali, dan tidak untuk nyeri akut',
            'faskes_tk1' => false,
            'faskes_tk2' => true,
            'faskes_tk3' => true,
            'category_id' => 3],
            ['generic_name' => 'asam mefenamat kaps',
            'form' => 'kaps 250 mg',
            'restriction_formula' => '30 kaps/bulan.',
            'description' => '',
            'faskes_tk1' => true,
            'faskes_tk2' => true,
            'faskes_tk3' => true,
            'category_id' => 4],
            ['generic_name' => 'asam mefenamat tab',
            'form' => 'tab 500 mg',
            'restriction_formula' => '30 tab/bulan.',
            'description' => '',
            'faskes_tk1' => true,
            'faskes_tk2' => true,
            'faskes_tk3' => true,
            'category_id' => 4],
            ['generic_name' => 'ibuprofen tab 200 mg',
            'form' => 'tab 200 mg',
            'restriction_formula' => '30 tab/bulan.',
            'description' => '',
            'faskes_tk1' => true,
            'faskes_tk2' => true,
            'faskes_tk3' => true,
            'category_id' => 4],
            ['generic_name' => 'alopurinol tab 100 mg',
            'form' => 'tab 100 mg',
            'restriction_formula' => '30 tab/bulan.',
            'description' => 'tidak diberikan pada saat nyeri akut',
            'faskes_tk1' => true,
            'faskes_tk2' => true,
            'faskes_tk3' => true,
            'category_id' => 5],
            ['generic_name' => 'alopurinol tab 300 mg',
            'form' => 'tab 300 mg',
            'restriction_formula' => '30 tab/bulan.',
            'description' => 'tidak diberikan pada saat nyeri akut',
            'faskes_tk1' => true,
            'faskes_tk2' => true,
            'faskes_tk3' => true,
            'category_id' => 5],
            ['generic_name' => 'kolkisin',
            'form' => 'tab 500 mg',
            'restriction_formula' => '30 tab/bulan.',
            'description' => 'tidak diberikan pada saat nyeri akut',
            'faskes_tk1' => true,
            'faskes_tk2' => true,
            'faskes_tk3' => true,
            'category_id' => 5],
            ['generic_name' => 'amitriptilin',
            'form' => 'tab 25 mg',
            'restriction_formula' => '30 tab/bulan.',
            'description' => '',
            'faskes_tk1' => true,
            'faskes_tk2' => true,
            'faskes_tk3' => true,
            'category_id' => 6],
            ['generic_name' => 'gabapentin kaps 100 mg',
            'form' => 'kaps 100 mg',
            'restriction_formula' => '60 tab/bulan.',
            'description' => 'Hanya untuk neuralgia pascaherpes atau nyeri neuropati diabetikum',
            'faskes_tk1' => false,
            'faskes_tk2' => true,
            'faskes_tk3' => true,
            'category_id' => 6],
            ['generic_name' => 'gabapentin kaps 300 mg',
            'form' => 'kaps 300 mg',
            'restriction_formula' => '30 tab/bulan.',
            'description' => 'Hanya untuk neuralgia pascaherpes atau nyeri neuropati diabetikum',
            'faskes_tk1' => false,
            'faskes_tk2' => true,
            'faskes_tk3' => true,
            'category_id' => 6],
            ['generic_name' => 'bupivakain',
            'form' => 'inj 0,5%',
            'restriction_formula' => '',
            'description' => '',
            'faskes_tk1' => false,
            'faskes_tk2' => true,
            'faskes_tk3' => true,
            'category_id' => 7],
            ['generic_name' => 'bupivakain heavy',
            'form' => 'inj 0,5% + glukosa 8%',
            'restriction_formula' => '',
            'description' => 'Khusus untuk analgesia spinal',
            'faskes_tk1' => false,
            'faskes_tk2' => true,
            'faskes_tk3' => true,
            'category_id' => 7],
            ['generic_name' => 'etil klorida',
            'form' => 'spray 100 mL',
            'restriction_formula' => '',
            'description' => '',
            'faskes_tk1' => true,
            'faskes_tk2' => true,
            'faskes_tk3' => true,
            'category_id' => 7],
            ['generic_name' => 'deksmedetomidin',
            'form' => 'inj 100 mcg/mL',
            'restriction_formula' => '',
            'description' => 'Untuk sedasi pada pasien di ICU, 
            kraniotomi, bedah jantung dan 
            operasi yang memerlukan waktu 
            pembedahan yang lama.',
            'faskes_tk1' => false,
            'faskes_tk2' => true,
            'faskes_tk3' => true,
            'category_id' => 8],
            ['generic_name' => 'desfluran',
            'form' => 'ih',
            'restriction_formula' => '',
            'description' => '',
            'faskes_tk1' => false,
            'faskes_tk2' => true,
            'faskes_tk3' => true,
            'category_id' => 8],
            ['generic_name' => 'halotan',
            'form' => 'ih',
            'restriction_formula' => '',
            'description' => 'Tidak boleh digunakan berulang dan tidak untuk pasien dengan 
            gangguan fungsi hati',
            'faskes_tk1' => false,
            'faskes_tk2' => true,
            'faskes_tk3' => true,
            'category_id' => 8],
            ['generic_name' => 'atropin',
            'form' => 'inj 0,25 mg/mL (i.v./s.k.)',
            'restriction_formula' => '',
            'description' => '',
            'faskes_tk1' => true,
            'faskes_tk2' => true,
            'faskes_tk3' => true,
            'category_id' => 9],
            ['generic_name' => 'diazepam',
            'form' => 'inj 5 mg/mL',
            'restriction_formula' => '',
            'description' => '',
            'faskes_tk1' => true,
            'faskes_tk2' => true,
            'faskes_tk3' => true,
            'category_id' => 9],
            ['generic_name' => 'midazolam',
            'form' => 'inj 1 mg/mL (i.v.)',
            'restriction_formula' => '- Dosis rumatan: <br>
                1 mg/jam (24 
                mg/hari).
                - Dosis premedikasi: <br>
                8 vial/kasus.',
            'description' => 'Dapat digunakan untuk premedikasi 
            sebelum induksi anestesi dan 
            rumatan selama anestesi umum.',
            'faskes_tk1' => false,
            'faskes_tk2' => true,
            'faskes_tk3' => true,
            'category_id' => 9],
            ['generic_name' => 'deksametason',
            'form' => 'inj 5 mg/mL',
            'restriction_formula' => '20 mg/hari',
            'description' => '',
            'faskes_tk1' => true,
            'faskes_tk2' => true,
            'faskes_tk3' => true,
            'category_id' => 10],
            ['generic_name' => 'difenhidramin',
            'form' => 'inj 10 mg/mL (i.v./i.m.)',
            'restriction_formula' => '30 mg/hari',
            'description' => '',
            'faskes_tk1' => true,
            'faskes_tk2' => true,
            'faskes_tk3' => true,
            'category_id' => 10],
            ['generic_name' => 'epinefrin (adrenalin)',
            'form' => 'inj 1 mg/mL',
            'restriction_formula' => '',
            'description' => '',
            'faskes_tk1' => true,
            'faskes_tk2' => true,
            'faskes_tk3' => true,
            'category_id' => 10],
            ['generic_name' => 'atropin tab 0,5 mg',
            'form' => 'tab 0,5 mg',
            'restriction_formula' => '',
            'description' => '',
            'faskes_tk1' => true,
            'faskes_tk2' => true,
            'faskes_tk3' => true,
            'category_id' => 11],
            ['generic_name' => 'atropin inj 0,25 mg/mL',
            'form' => 'inj 0,25 mg/mL (i.v.)',
            'restriction_formula' => '',
            'description' => '',
            'faskes_tk1' => true,
            'faskes_tk2' => true,
            'faskes_tk3' => true,
            'category_id' => 11],
            ['generic_name' => 'efedrin',
            'form' => 'inj 50 mg/mL',
            'restriction_formula' => '',
            'description' => '',
            'faskes_tk1' => false,
            'faskes_tk2' => true,
            'faskes_tk3' => true,
            'category_id' => 11],
            ['generic_name' => 'magnesium sulfat',
            'form' => 'serb',
            'restriction_formula' => '',
            'description' => '',
            'faskes_tk1' => true,
            'faskes_tk2' => true,
            'faskes_tk3' => true,
            'category_id' => 12],
        ]);
    }
}
